### ISSUE TITLE
CertFactory cannot certify an ML-DSA key: naming Bouncy Castle refuses a JDK-generated post-quantum key

### ISSUE THREAD

**Issue by astrapi69** [astrapi69/crypt-data#33]
Found by building `mystic-crypt` against the released 12.1 - which is the check that should have run before the release and did not. Four of its tests fail:

```
KeystoreAddKeyPairCommandTest  [6] AddCase[algorithm=ML-DSA-44, type=PKCS12]  expected: <0> but was: <1>
KeystoreAddKeyPairCommandTest  [7] AddCase[algorithm=ML-DSA-65, ...]          expected: <0> but was: <1>
KeystoreAddKeyPairCommandTest  [8] AddCase[algorithm=ML-DSA-87, ...]          expected: <0> but was: <1>
KeystoreAddKeyPairCommandTest  [9] AddCase[algorithm=ml_dsa_65, ...]          expected: <0> but was: <1>
```

## Measured against 12.1

```
ML-DSA-44      days    OperatorCreationException: cannot create signer: unknown private key passed to ML-DSA
ML-DSA-44      dated   OperatorCreationException: cannot create signer: unknown private key passed to ML-DSA
SHA256withRSA  days    ok
SHA256withRSA  dated   ok
```

## Two findings, not one

**The days overload is a regression I introduced in #28.** Before it, `newX509CertificateV3(KeyPair, X500Name, int daysToBeValid, ...)` built its content signer without naming a provider, so the JDK answered - and the JDK has had ML-DSA since 24. #28 named Bouncy Castle to fix EC curves the JDK does not implement, and thereby refused post-quantum keys the JDK does. `KeystoreCommand` in mystic-crypt is the only caller of that overload, and it is exactly the one that broke.

**The other three signer sites were already broken for ML-DSA**, before #28 and before 12.1. They named Bouncy Castle from the start, so the dated overload has never been able to certify an ML-DSA key. #28 did not cause that; it made all four consistent, in the wrong direction.

## Why naming a provider unconditionally cannot work

Neither provider covers the whole set:

- Bouncy Castle knows EC curves the JDK does not implement - prime239v1, secp256k1 (#28)
- The JDK generates ML-DSA keys that Bouncy Castle refuses to sign with

So the signer has to try one and fall back to the other. `mystic-crypt` already learned this and does it in `SelfSignedCertificateFactory.newSigner`:

```java
try
{
    return new JcaContentSignerBuilder(signatureAlgorithm)
        .setProvider(BouncyCastleProvider.PROVIDER_NAME).build(keyPair.getPrivate());
}
catch (...)
{
    // fall back to whichever provider does know this key
}
```

That is the shape all four sites in `CertFactory` need.

## On the process

12.1 went out without the downstream ever having compiled against it. Building `mystic-crypt` against a locally published snapshot would have caught this before the release rather than after; that is what will happen for the fix.

Since a published version cannot be replaced, this needs a 12.2.
